source 'https://github.com/forestfsl/SegmentSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'APIKit_Example' do
  pod 'APIKit', :path => '../'
    pod 'IQKeyboardManager'
    pod 'SLCategory'
    pod 'SLWebEngine'
    pod 'CTMediatoKit'
#
#  target 'APIKit_Tests' do
#    inherit! :search_paths
#
#
#  end
end
